# Generated by Django 3.2.12 on 2024-01-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskToBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scavengerhunt.board')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scavengerhunt.task')),
            ],
            options={
                'unique_together': {('board', 'position_x', 'position_y')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ManyToManyField(related_name='tasks', through='scavengerhunt.TaskToBoard', to='scavengerhunt.Board'),
        ),
    ]
